### ISSUE TITLE
Received a DNS error when trying to access Claire from one machine

### ISSUE THREAD

**Issue by BTMurphy** [42sixsolutions/claire#149]
I only received this error on one machine (MacBook Air with Yosemite, using Chrome 43). I couldn't replicate the error on any other machine. I don't think we should try to track down this error at this time.

![image](https://cloud.githubusercontent.com/assets/12994909/8380197/7bd7d4d8-1bf2-11e5-88b6-2256cda8a78a.png)

**Comment by ghochard42six** [comment]
This happens when openshift is rebuilding after a push
