### ISSUE TITLE
Design Drug Views

### ISSUE THREAD

**Issue by ghochard42six** [42sixsolutions/claire#17]
Given the data of: Adverse Events, Recalls, Positive Tweets, Negative Tweets, (Neither) Tweets ... what other displays would be useful rather than the timeline.

**Comment by ghochard42six** [comment]
![1-selection](https://cloud.githubusercontent.com/assets/5137806/8305058/78b5dfa0-1979-11e5-88fc-f8f0238ed2ee.jpg)
![2-details](https://cloud.githubusercontent.com/assets/5137806/8305059/78b76b54-1979-11e5-9651-3cf07ddffa68.jpg)

**Comment by dbeck42six** [comment]
![1-selection](https://cloud.githubusercontent.com/assets/1770879/8314868/753c0200-19ba-11e5-8fae-d1c12029fded.jpg)
![2-details](https://cloud.githubusercontent.com/assets/1770879/8314869/753d7180-19ba-11e5-8b68-bef6cc129ff1.jpg)

**Comment by mhoward** [comment]
![1-selection](https://cloud.githubusercontent.com/assets/4072758/8339788/2479385a-1a88-11e5-8c2c-d9448b56c76a.jpg)
![2-b-details-full](https://cloud.githubusercontent.com/assets/4072758/8339791/28bcaf1e-1a88-11e5-8ac5-f2306810d11a.jpg)
