### ISSUE TITLE
Store documentation in repository

### ISSUE THREAD

**Issue by BTMurphy** [42sixsolutions/claire#35]

**Comment by ghochard42six** [comment]
What specific documentation artifacts?  Separate GIT branch or wiki?

**Comment by BTMurphy** [comment]
I think the wiki or Github pages would be clearer than a separate GIT branch.

We need:
1. Installation guide
2. Screenshots or URL to Travis and Jenkins
3. Screenshots or URL to continuous monitoring tools
4. Screenshots or other evidence of usability tests

**Comment by BTMurphy** [comment]
Documentation in root, claire-agile, and claire-ui. We did not take screenshots of the CI or continuous monitoring tools.
